services:
    nfq_fairytale.action.collection.count:
        class: Nfq\Fairytale\ApiBundle\Actions\CollectionCountAction
        calls:
            - [setFactory, [@nfq_fairytale.datasource.factory]]
        tags:
            - { name: nfq_fairytale.api.action.collection, resource: *, action: count, method: GET }

    nfq_fairytale.api.action.instance.read:
        class: Nfq\Fairytale\ApiBundle\Actions\Instance\ReadAction
        calls:
            - [setFactory, [@nfq_fairytale.datasource.factory]]
        tags:
            - { name: nfq_fairytale.api.action.instance, resource: *, method: GET }

    nfq_fairytale.api.action.instance.delete:
        class: Nfq\Fairytale\ApiBundle\Actions\Instance\DeleteAction
        calls:
            - [setFactory, [@nfq_fairytale.datasource.factory]]
        tags:
            - { name: nfq_fairytale.api.action.instance, resource: *, method: DELETE }

    nfq_fairytale.api.action.instance.update:
        class: Nfq\Fairytale\ApiBundle\Actions\Instance\UpdateAction
        calls:
            - [setFactory, [@nfq_fairytale.datasource.factory]]
        tags:
            - { name: nfq_fairytale.api.action.instance, resource: *, method: UPDATE }

