services:
    nfq_fairytale.action.collection.count:
        class: Nfq\Fairytale\ApiBundle\Actions\Collection\CountAction
        tags:
            - { name: nfq_fairytale.api.action.collection, resource: '*', action: count, method: GET }

    nfq_fairytale.api.action.instance.read:
        class: Nfq\Fairytale\ApiBundle\Actions\Instance\ReadAction
        tags:
            - { name: nfq_fairytale.api.action.instance, resource: '*', method: GET }

    nfq_fairytale.api.action.instance.delete:
        class: Nfq\Fairytale\ApiBundle\Actions\Instance\DeleteAction
        tags:
            - { name: nfq_fairytale.api.action.instance, resource: '*', method: DELETE }

    nfq_fairytale.api.action.instance.update:
        class: Nfq\Fairytale\ApiBundle\Actions\Instance\UpdateAction
        tags:
            - { name: nfq_fairytale.api.action.instance, resource: '*', method: PUT }

    nfq_fairytale.api.action.collection.create:
        class: Nfq\Fairytale\ApiBundle\Actions\Collection\CreateAction
        tags:
            - { name: nfq_fairytale.api.action.collection, resource: '*', method: POST }

    nfq_fairytale.api.action.collection.index:
        class: Nfq\Fairytale\ApiBundle\Actions\Collection\IndexAction
        tags:
            - { name: nfq_fairytale.api.action.collection, resource: '*', method: GET }

    # TODO: move to CoreBundle (right now compiler pass does not see those *.yml)
    nfq_fairytale.action.user.books.list:
        class: Nfq\Fairytale\CoreBundle\Actions\User\ListBooks
        calls:
            - [setSecurityContext, [@security.context]]
        tags:
            - { name: nfq_fairytale.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\User", action: books, method: GET }

    nfq_fairytale.action.user.reservation.get:
        class: Nfq\Fairytale\CoreBundle\Actions\User\GetReservation
        calls:
            - [setFactory, [@nfq_fairytale.data_source.factory]]
        tags:
            - { name: nfq_fairytale.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\User", action: reservation, method: GET }
