services:
    nfq_fairytale.api.listener.logging:
        class: Nfq\Fairytale\ApiBundle\EventListener\LoggingListener
        calls:
            - [setContext, [@security.context]]
            - [setLogger, [@logger]]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: monolog.logger, channel: api }

    nfq_fairytale.api.listener.auth:
        class: Nfq\Fairytale\ApiBundle\EventListener\AuthorizationListener
        calls:
            - [setSecurityContext, [@security.context]]
            - [setCredentials, [@nfq_fairytale.api.security.credential_store]]
            - [setResourceResolver, [@nfq_fairytale.api.resource_resolver]]
            - [setActionResolver, [@nfq_fairytale.action.manager]]
            - [setSerializer, [@jms_serializer]]
            - [setLogger, [@logger]]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: api }
