services:
    nfq_fairytale.api.listener.auth:
        class: Nfq\Fairytale\ApiBundle\EventListener\Authorization
        calls:
            - [setContext, [@security.context]]
            - [setLogger, [@logger]]
            - [setCredentialStore, [@nfq_fairytale.api.security.credential_store]]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: monolog.logger, channel: api }

    nfq_fairytale.api.listener.response_builder:
        class: Nfq\Fairytale\ApiBundle\EventListener\ResponseBuilder
        calls:
            - [setSerializer, [@jms_serializer]]
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

    nfq_fairytale.api.listener.request_format:
        class: Nfq\Fairytale\ApiBundle\EventListener\RequestFormat
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
