services:
    nfq_fairytale.api.listener.auth:
        class: Nfq\Fairytale\ApiBundle\EventListener\Authorization
        calls:
            - [setContext, [@security.context]]
            - [setLogger, [@logger]]
        tags:
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: monolog.logger, channel: api }
