nfq_fairytale_api.resource.instance.action:
    path:     /{resource}/{identifier}/{actionName}
    defaults:
        _controller: nfq_fairytale.api.controller:customAction
    methods: [GET, POST, PUT, DELETE, HEAD]
    requirements:
        identifier: \d+

nfq_fairytale_api.resource.instance.action.empty_action:
    path:     /{resource}/{identifier}
    defaults:
        _controller: nfq_fairytale.api.controller:customAction
        actionName: ~
    methods: [GET, POST, PUT, DELETE, HEAD]
    requirements:
        identifier: \d+

nfq_fairytale_api.resource.collection.action:
    path:     /{resource}/{actionName}
    defaults: { _controller: nfq_fairytale.api.controller:customAction }
    methods: [GET, POST, PUT, DELETE, HEAD]

nfq_fairytale_api.resource.collection.action.empty_action:
    path:     /{resource}/{actionName}
    defaults:
        _controller: nfq_fairytale.api.controller:customAction
        actionName: ~
    methods: [GET, POST, PUT, DELETE, HEAD]
