nfq_fairytale_api.resource.index:
    path:     /{resource}
    defaults: { _controller: NfqFairytaleApiBundle:Api:index }
    requirements:
        method: GET

nfq_fairytale_api.resource.create:
    path:     /{resource}
    defaults: { _controller: NfqFairytaleApiBundle:Api:create }
    requirements:
        method: POST

nfq_fairytale_api.resource.read:
    path:     /{resource}/{identifier}
    defaults: { _controller: nfq_fairytale.api.controller:readAction }
    requirements:
        method: GET

nfq_fairytale_api.resource.update:
    path:     /{resource}/{identifier}
    defaults: { _controller: NfqFairytaleApiBundle:Api:update }
    requirements:
        method: PUT

nfq_fairytale_api.resource.delete:
    path:     /{resource}/{identifier}
    defaults: { _controller: NfqFairytaleApiBundle:Api:delete }
    requirements:
        method: DELETE
