nfq_fairytale_api.resource.index:
    path:     /{resource}
    defaults: { _controller: nfq_fairytale.api.controller:indexAction }
    methods: [GET]

nfq_fairytale_api.resource.create:
    path:     /{resource}
    defaults: { _controller: nfq_fairytale.api.controller:createAction }
    methods: [POST]

nfq_fairytale_api.resource.read:
    path:     /{resource}/{identifier}
    defaults: { _controller: nfq_fairytale.api.controller:readAction }
    methods: [GET]

nfq_fairytale_api.resource.update:
    path:     /{resource}/{identifier}
    defaults: { _controller: nfq_fairytale.api.controller:updateAction }
    methods: [PUT]

nfq_fairytale_api.resource.delete:
    path:     /{resource}/{identifier}
    defaults: { _controller: nfq_fairytale.api.controller:deleteAction }
    methods: [DELETE]
