parameters:
#    nfq_fairytale_api.example.class: Nfq\Fairytale\ApiBundle\Example

services:
#    nfq_fairytale_api.example:
#        class: %nfq_fairytale_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
