parameters:

services:
    nfq_fairytale.datasource.file:
        class: Nfq\Fairytale\ApiBundle\Datasource\FileSource
        calls:
            - [setLocator, [@kernel]]

    nfq_fairytale.datasource.doctrine.orm.class_factory:
        class: Nfq\Fairytale\ApiBundle\Datasource\ClassFactory

    nfq_fairytale.datasource.orm:
        class: Nfq\Fairytale\ApiBundle\Datasource\DoctrineOrmSource
        calls:
            - [setClassFactory, [@nfq_fairytale.datasource.doctrine.orm.class_factory]]
            - [setEntityManager, [@doctrine.orm.default_entity_manager]]

    nfq_fairytale.datasource.factory:
        class: Nfq\Fairytale\ApiBundle\Datasource\Factory\DatasourceFactory


    nfq_fairytale.action.collection.count:
        class: Nfq\Fairytale\ApiBundle\Actions\CollectionCountAction
        calls:
            - [setFactory, [@nfq_fairytale.datasource.factory]]

    nfq_fairytale.actions.manager:
        class: Nfq\Fairytale\ApiBundle\Actions\ActionManager
        calls:
            - [addResourceAction, [@nfq_fairytale.action.count, "*", "count", "GET"]]

    nfq_fairytale.api.controller:
        class: Nfq\Fairytale\ApiBundle\Controller\ApiController
        calls:
            - [setMapping, [%nfq_fairytale_api.config.mapping%]]
            - [setDatasourceFactory, [@nfq_fairytale.datasource.factory]]
            - [setDefaultIndexSize, [%nfq_fairytale_api.config.default_index_size%]]
            - [setActionManager, [@nfq_fairytale.actions.manager]]
