parameters:

services:
    nfq_fairytale.api.security.credential_store:
        class: Nfq\Fairytale\ApiBundle\Security\CredentialStore
        calls:
            - [setAcl, [%nfq_fairytale_api.config.security.acl%]]
            - [setDefaultCredential, [%nfq_fairytale_api.config.security.default_credential%]]
            - [setRoleHierarchy, [@security.role_hierarchy]]

    nfq_fairytale.datasource.file:
        class: Nfq\Fairytale\ApiBundle\Datasource\FileSource
        calls:
            - [setLocator, [@kernel]]

    nfq_fairytale.datasource.doctrine.orm.class_factory:
        class: Nfq\Fairytale\ApiBundle\Datasource\ClassFactory

    nfq_fairytale.datasource.orm:
        class: Nfq\Fairytale\ApiBundle\Datasource\DoctrineOrmSource
        calls:
            - [setClassFactory, [@nfq_fairytale.datasource.doctrine.orm.class_factory]]
            - [setEntityManager, [@doctrine.orm.default_entity_manager]]

    nfq_fairytale.datasource.factory:
        class: Nfq\Fairytale\ApiBundle\Datasource\Factory\DatasourceFactory

    nfq_fairytale.action.collection.count:
        class: Nfq\Fairytale\ApiBundle\Actions\CollectionCountAction
        calls:
            - [setFactory, [@nfq_fairytale.datasource.factory]]
        tags:
            - { name: nfq_fairytale.api.action.collection, resource: *, action: count, method: GET }

    nfq_fairytale.action.manager:
        class: Nfq\Fairytale\ApiBundle\Actions\ActionManager

    nfq_fairytale.api.resource_resolver:
        class: Nfq\Fairytale\ApiBundle\Helper\ResourceResolver
        calls:
            - [setResourceMapping, [%nfq_fairytale_api.config.mapping%]]

    nfq_fairytale.api.action_resolver:
        class: Nfq\Fairytale\ApiBundle\Helper\ActionResolver

    nfq_fairytale.api.controller:
        class: Nfq\Fairytale\ApiBundle\Controller\ApiController
        calls:
            - [setResolver, [@nfq_fairytale.api.resource_resolver]]
            - [setDatasourceFactory, [@nfq_fairytale.datasource.factory]]
            - [setDefaultIndexSize, [%nfq_fairytale_api.config.default_index_size%]]
            - [setActionManager, [@nfq_fairytale.action.manager]]
