parameters:

services:
    nfq_fairytale.datasource.file:
        class: Nfq\Fairytale\ApiBundle\Datasource\FileSource
        calls:
            - [setLocator, [@kernel]]

    nfq_fairytale.datasource.doctrine.orm.class_factory:
        class: Nfq\Fairytale\ApiBundle\Datasource\ClassFactory

    nfq_fairytale.datasource.doctrine.orm:
        class: Nfq\Fairytale\ApiBundle\Datasource\DoctrineOrmSource
        calls:
            - [setClassFactory, [@nfq_fairytale.datasource.doctrine.orm.class_factory]]
