parameters:

services:
    nfq_fairytale.data_source.doctrine.orm.class_factory:
        class: Nfq\Fairytale\ApiBundle\DataSource\ClassFactory

    nfq_fairytale.data_source.orm:
        class: Nfq\Fairytale\ApiBundle\DataSource\DoctrineOrmSource
        calls:
            - [setClassFactory, [@nfq_fairytale.data_source.doctrine.orm.class_factory]]
            - [setRegistry, [@doctrine]]

    nfq_fairytale.data_source.factory:
        class: Nfq\Fairytale\ApiBundle\DataSource\Factory\DataSourceFactory

    nfq_fairytale.action.manager:
        class: Nfq\Fairytale\ApiBundle\Actions\ActionManager

    nfq_fairytale.api.resource_resolver:
        class: Nfq\Fairytale\ApiBundle\Helper\ResourceResolver
        calls:
            - [setResourceMapping, [%nfq_fairytale_api.config.mapping%]]

    nfq_fairytale.api.security.permissions:
        class: Nfq\Fairytale\ApiBundle\Security\PermissionManager
        calls:
            - [setAcl, [%nfq_fairytale_api.config.security.acl%]]

    nfq_fairytale.api.security.request_validator:
        class: Nfq\Fairytale\ApiBundle\Helper\RequestValidator
        calls:
            - [setPermissions, [@nfq_fairytale.api.security.permissions]]

    nfq_fairytale.api.security.response_filter:
        class: Nfq\Fairytale\ApiBundle\Helper\ResponseFilter
        calls:
            - [setPermissions, [@nfq_fairytale.api.security.permissions]]
            - [setSerializer, [@jms_serializer]]
