language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - composer install -n --prefer-dist

script: bin/phpspec run -v -fpretty

cache:
    directories:
        - $HOME/.composer/cache/
