language: php

php:
    - 5.5

before_install:
    - mkdir -p app/cache/
    - mkdir -p app/logs/
    - sudo chmod 0777 -R app/*

install:
    - composer install -n --prefer-source

before_script:
    - "sed -i 's/database_password: 123/database_password: ~/g' app/config/parameters.yml"
    - app/console doctrine:database:create -e test

script:
#    - bin/phpspec run -v -fpretty
    - bin/behat -fpretty
