language: php

php:
    - 5.4
    - 5.5
    - 5.6

addons:
    hosts:
        - fairytale
        - fairytale.dev

before_script:
    - wget https://apt.puppetlabs.com/puppetlabs-release-precise.deb
    - sudo dpkg -i puppetlabs-release-precise.deb
    - sudo apt-get update
    - sudo apt-get install puppet
    - gem install librarian-puppet
    - cd .vagrant && librarian-puppet install && librarian-puppet show && cd ..
    - cat /etc/puppet/puppet.conf
    - sudo puppet apply .vagrant/manifests/default.pp --modulepath .vagrant/modules/ --parser future
    - composer install -n --prefer-source
    - sudo service nginx restart

script:
    - bin/phpspec run -v -fpretty
#    - php bin/behat @NfqFairytaleApiBundle -v
    - curl http://localhost/ --fail

after_script:
    - cat /var/log/nginx/fairytale.dev.error.log
    - cat /var/log/nginx/fairytale.dev.access.log
    - cat /var/www/fairytale.dev/app/logs/dev.log
    - cat /etc/nginx/sites-enabled/fairytale.dev.conf
    - cat /etc/nginx/nginx.conf
    - ls -la /var/run/
