language: php

php:
#    - 5.4
#    - 5.5
    - 5.6

before_script:
    - wget https://apt.puppetlabs.com/puppetlabs-release-precise.deb
    - sudo dpkg -i puppetlabs-release-precise.deb
    - sudo apt-get update
    - sudo apt-get install puppet
    - gem install librarian-puppet
    - cd .vagrant && librarian-puppet install && librarian-puppet show && cd ..
    - puppet help
    - cat /etc/puppet/puppet.conf
    - sudo puppet apply -v .vagrant/manifests/default.pp --modulepath .vagrant/modules/ --parser future
    - composer install -n --prefer-source
    - sudo service nginx restart # most likely unneeded

script:
    - bin/phpspec run -v -fpretty
    - php bin/behat @NfqFairytaleApiBundle -v

after_script:
    - curl http://localhost/
    - tail /var/log/nginx/fairytale.dev.error.log -n 100
    - tail /var/www/fairytale.dev/app/logs/dev.log
    - cat /etc/nginx/sites-enabled/fairytale.dev.conf
