language: php

php:
    - 5.4
    - 5.5
    - 5.6

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.5
    - php: 5.6

addons:
    hosts:
        - fairytale
        - fairytale.dev

before_script:
    - mkdir -p app/cache/
    - mkdir -p app/logs/
    - sudo chmod 0777 -R app/*
    - composer install -n --prefer-source
    - app/console doctrine:database:create -e test

script:
    - bin/phpspec run -v -fpretty
    - bin/behat -fpretty

after_script:
    - cat /var/www/fairytale.dev/app/logs/dev.log
    - cat /var/www/fairytale.dev/app/logs/test.log
