language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm

addons:
    hosts:
        - fairytale
        - fairytale.dev

before_install:
    - sed -i 's/database_password: 123/database_password: ~/g' app/config/parameters.yml
    - mkdir -p app/cache/
    - mkdir -p app/logs/
    - sudo chmod 0777 -R app/*

install:
    - composer install -n --prefer-source

before_script:
    - app/console doctrine:database:create -e test

script:
    - bin/phpspec run -v -fpretty
    - bin/behat -fpretty

after_script:
    - cat /var/www/fairytale.dev/app/logs/dev.log
    - cat /var/www/fairytale.dev/app/logs/test.log
