language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - composer install -n
    - wget https://scrutinizer-ci.com/ocular.phar


script:
    - bin/phpunit -c app
    - bin/phpcs -p --standard=PSR2 src/

cache:
    directories:
        - vendor/

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover app/build/logs/clover.xml
