services:
    nfq_fairytale.action.user.reservation.get:
        class: Nfq\Fairytale\CoreBundle\Actions\User\GetReservation
        tags:
            - { name: nfq_fairytale.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\User", action: reservation, method: GET }

    nfq_fairytale.action.user.now_reading.get:
        class: Nfq\Fairytale\CoreBundle\Actions\User\GetNowReading
        calls:
            - [setFactory, [@nfq_fairytale.data_source.factory]]
        tags:
            - { name: nfq_fairytale.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\User", action: reading, method: GET }
