services:
    nfq_fairytale.action.user.reservation.get:
        class: Nfq\Fairytale\CoreBundle\Actions\User\GetReservation
        tags:
            - { name: nfq_fairytale.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\User", action: reservation, method: GET }

    nfq_fairytale.action.user.now_reading.get:
        class: Nfq\Fairytale\CoreBundle\Actions\User\GetNowReading
        calls:
            - [setFactory, [@nfq_fairytale.data_source.factory]]
        tags:
            - { name: nfq_fairytale.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\User", action: reading, method: GET }

    nfq_fairytale.action.user.returned.list:
        class: Nfq\Fairytale\CoreBundle\Actions\User\GetReturnedBooks
        tags:
            - { name: nfq_fairytale.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\User", action: returned, method: GET }

    nfq_fairytale.action.user.categories.list:
        class: Nfq\Fairytale\CoreBundle\Actions\User\GetCategories
        tags:
            - { name: nfq_fairytale.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\User", action: categories, method: GET }

    nfq_fairytale.action.category.books.list:
        class: Nfq\Fairytale\CoreBundle\Actions\Category\GetBooks
        calls:
            - [setFactory, [@nfq_fairytale.data_source.factory]]
        tags:
            - { name: nfq_fairytale.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\Category", action: books, method: GET }

    nfq_fairytale.action.book.details:
        class: Nfq\Fairytale\CoreBundle\Actions\Book\GetDetails
        tags:
            - { name: nfq_fairytale.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\Book", action: details, method: GET }
