parameters:
    nfq_fairytale.action.user.details.image_filters:
        - user_medium
        - user_small

    nfq_fairytale.action.book.details.image_filters:
        - book_big
        - book_medium
        - book_small
        - book_tiny

services:
    nfq_fairytale.action.user.details:
        class: Nfq\Fairytale\CoreBundle\Actions\User\GetDetails
        tags:
            - { name: im0rtality_api.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\User", method: GET }
        calls:
            - [setCacheManager, [@liip_imagine.cache.manager]]
            - [setFilters, [%nfq_fairytale.action.user.details.image_filters%]]

    nfq_fairytale.action.user.reservation.get:
        class: Nfq\Fairytale\CoreBundle\Actions\User\GetReservation
        tags:
            - { name: im0rtality_api.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\User", action: reservation, method: GET }
        calls:
            - [setCacheManager, [@liip_imagine.cache.manager]]
            - [setFilters, [%nfq_fairytale.action.book.details.image_filters%]]

    nfq_fairytale.action.user.now_reading.get:
        class: Nfq\Fairytale\CoreBundle\Actions\User\GetNowReading
        calls:
            - [setCacheManager, [@liip_imagine.cache.manager]]
            - [setFilters, [%nfq_fairytale.action.book.details.image_filters%]]
        tags:
            - { name: im0rtality_api.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\User", action: reading, method: GET }

    nfq_fairytale.action.user.returned.list:
        class: Nfq\Fairytale\CoreBundle\Actions\User\GetReturnedBooks
        tags:
            - { name: im0rtality_api.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\User", action: returned, method: GET }
        calls:
            - [setCacheManager, [@liip_imagine.cache.manager]]
            - [setFilters, [%nfq_fairytale.action.book.details.image_filters%]]

    nfq_fairytale.action.user.categories.list:
        class: Nfq\Fairytale\CoreBundle\Actions\User\GetCategories
        tags:
            - { name: im0rtality_api.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\User", action: categories, method: GET }

    nfq_fairytale.action.category.details:
        class: Nfq\Fairytale\CoreBundle\Actions\Category\GetDetails
        calls:
            - [setCacheManager, [@liip_imagine.cache.manager]]
            - [setFilters, [%nfq_fairytale.action.book.details.image_filters%]]
        tags:
            - { name: im0rtality_api.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\Category", method: GET }

    nfq_fairytale.action.book.details:
        class: Nfq\Fairytale\CoreBundle\Actions\Book\GetDetails
        tags:
            - { name: im0rtality_api.api.action.instance, resource: "Nfq\Fairytale\CoreBundle\Entity\Book", method: GET }
        calls:
            - [setCacheManager, [@liip_imagine.cache.manager]]
            - [setFilters, [%nfq_fairytale.action.book.details.image_filters%]]

    nfq_fairytale.action.book.popular:
        class: Nfq\Fairytale\CoreBundle\Actions\Book\GetMostPopular
        tags:
            - { name: im0rtality_api.api.action.collection, resource: "Nfq\Fairytale\CoreBundle\Entity\Book", action: popular, method: GET }
        calls:
            - [setCacheManager, [@liip_imagine.cache.manager]]
            - [setFilters, [%nfq_fairytale.action.book.details.image_filters%]]

    nfq_fairytale.action.book.new:
        class: Nfq\Fairytale\CoreBundle\Actions\Book\GetNewest
        tags:
            - { name: im0rtality_api.api.action.collection, resource: "Nfq\Fairytale\CoreBundle\Entity\Book", action: new, method: GET }
        calls:
            - [setCacheManager, [@liip_imagine.cache.manager]]
            - [setFilters, [%nfq_fairytale.action.book.details.image_filters%]]
