Fairytale\CoreBundle\Entity\Book:
    type: entity
    id:
        id:
            type: integer
            generator:
            strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        year:
            type: integer
            length: 4
    oneToOne:
        proposal:
            targetEntity: Book
            inversedBy: book
    manyToMany:
        categories:
            targetEntity: Category
            mappedBy: books
        authors:
            targetEntity: Author
            mappedBy: books
    lifecycleCallbacks: {}
