Fairytale\CoreBundle\Entity\Category:
    type: entity
    id:
        id:
            type: integer
            generator:
            strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToMany:
        books:
            targetEntity: Book
            inversedBy: categories
            joinTable:
                name: BookCategories
                joinColumns:
                    category_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    book_id:
                        referencedColumnName: id
    lifecycleCallbacks: {}
