Fairytale\CoreBundle\Entity\Rating:
    type: entity
    id:
        id:
            type: integer
            generator:
            strategy: AUTO
    fields:
        starCount:
            type: smallint
    manyToOne:
        user:
            targetEntity: User
            inversedBy: ratings
    lifecycleCallbacks: {}
