nfq_fairytale_api:
    security:
        default_credential: ROLE_SUPER_ADMIN
        acl:
            NfqFairytaleCoreBundle:
                User:
                    instance.delete:
                        status: ROLE_ADMIN
                    collection.index:
                        id:     ROLE_USER
                        name:   ROLE_USER
                        email:  ROLE_ADMIN
                    instance.read:
                        id:     ROLE_USER
                        name:   ROLE_USER
                        email:  ROLE_ADMIN
                    instance.create:
                        id:     ROLE_ADMIN
                        name:   ROLE_ADMIN
                        email:  ROLE_ADMIN
                    instance.update:
                        id:     ROLE_SUPER_USER
                        name:   ROLE_ADMIN
                        email:  ROLE_ADMIN
                    collection.count:
                        count:  ROLE_USER
