nfq_fairytale_api:
    security:
        default_credential: ROLE_SUPER_ADMIN
        acl:
            NfqFairytaleCoreBundle:
                User:
                    instance.read:
                        id: ROLE_USER
                        name: ROLE_USER
                        email: ROLE_ADMIN
                    collection.count:
                        count: ROLE_USER
