Nfq\Fairytale\CoreBundle\Entity:
    User:
        user.details:
            read:
                id:         ROLE_USER
                name:       ROLE_USER
                lastname:   ROLE_USER
                email:      ROLE_USER
                reservations: ROLE_USER
                comments:   ROLE_USER
                ratings:    ROLE_USER
                image:      ROLE_USER
            write:  ROLE_ADMIN
        instance.delete:
            read:
                status:     ROLE_ADMIN
        collection.index:
            read:
                id:         ROLE_USER
                name:       ROLE_USER
                lastname:   ROLE_USER
                email:      ROLE_ADMIN
                image:      ROLE_USER
        collection.create:
            read:
                id:         ROLE_ADMIN
                name:       ROLE_ADMIN
                lastname:   ROLE_ADMIN
                username:   ROLE_ADMIN
                email:      ROLE_ADMIN
                password:   ROLE_ADMIN
                image:      ROLE_ADMIN
            write:
                id:         ROLE_ADMIN
                name:       ROLE_ADMIN
                lastname:   ROLE_ADMIN
                username:   ROLE_ADMIN
                email:      ROLE_ADMIN
                password:   ROLE_ADMIN
                image:      ROLE_ADMIN
        instance.update:
            read:
                id:         ROLE_OWNER
                name:       ROLE_OWNER
                lastname:   ROLE_OWNER
                username:   ROLE_OWNER
                email:      ROLE_OWNER
                password:   ROLE_OWNER
                image:      ROLE_OWNER
            write:
                id:         ROLE_ADMIN
                name:       ROLE_OWNER
                lastname:   ROLE_OWNER
                username:   ROLE_ADMIN
                email:      ROLE_OWNER
                password:   ROLE_OWNER
                image:      ROLE_OWNER
        collection.count:
            read:
                count:      ROLE_USER
        user.reservation:
            read:
                id:         ROLE_USER
                title:      ROLE_USER
                categories: ROLE_USER
                authors:    ROLE_USER
                description: ROLE_USER
                pages:      ROLE_USER
                publisher:  ROLE_USER
                isbn:       ROLE_USER
                cover:      ROLE_USER
                language:   ROLE_USER
                image:      ROLE_USER
                status:     ROLE_USER
        user.now_reading:
            read:
                id:         ROLE_USER
                title:      ROLE_USER
                categories: ROLE_USER
                description: ROLE_USER
                pages:      ROLE_USER
                publisher:  ROLE_USER
                isbn:       ROLE_USER
                cover:      ROLE_USER
                authors:    ROLE_USER
                language:   ROLE_USER
                image:      ROLE_USER
                status:     ROLE_USER
            write: ROLE_USER
        user.returned:
            read:
                id:         ROLE_USER
                title:      ROLE_USER
                categories: ROLE_USER
                authors:    ROLE_USER
                description: ROLE_USER
                pages:      ROLE_USER
                publisher:  ROLE_USER
                isbn:       ROLE_USER
                cover:      ROLE_USER
                language:   ROLE_USER
                image:      ROLE_USER
                status:     ROLE_USER
        user.categories:
            read:
                id:         ROLE_USER
                title:      ROLE_USER
                count:      ROLE_USER
    Category:
        collection.index:
            read:
                id:         ROLE_USER
                title:      ROLE_USER
        category.details:
            read:
                id:         ROLE_USER
                title:      ROLE_USER
                books:      ROLE_USER
        category.new:
            read:
                id:         ROLE_USER
                title:      ROLE_USER
                books:      ROLE_USER
        category.popular:
            read:
                id:         ROLE_USER
                title:      ROLE_USER
                books:      ROLE_USER
        category.all:
            read:
                id:         ROLE_USER
                title:      ROLE_USER
                books:      ROLE_USER
    Book:
        collection.index:
            read:
                id:         ROLE_USER
                title:      ROLE_USER
        category.books:
            read:
                id:         ROLE_USER
        book.comment:
            read:
                id:           ROLE_USER
                content:      ROLE_USER
                user:         ROLE_USER
                book:         ROLE_USER
            write:
                content:      ROLE_USER
        book.details:
            read:
                id:         ROLE_USER
                title:      ROLE_USER
                categories: ROLE_USER
                description: ROLE_USER
                pages:      ROLE_USER
                publisher:  ROLE_USER
                isbn:       ROLE_USER
                cover:      ROLE_USER
                language:   ROLE_USER
                image:      ROLE_USER
                status:     ROLE_USER
                authors:    ROLE_USER
                ratings:    ROLE_USER
                comments:   ROLE_USER
        book.search:
            read:
                id:         ROLE_USER
                title:      ROLE_USER
                image:      ROLE_USER
                authors:    ROLE_USER
