imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

nfq_fairytale_api:
    mapping:
        user: NfqFairytaleCoreBundle:User
        testItem: testItem
    data:
        type: orm
        source: default
