imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: allyourbasebelongtous
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ NfqFairytaleFrontendBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Nfq\Fairytale\CoreBundle\Entity\User

nfq_fairytale_api:
    acl: api_acl.yml
    mapping:
        user: Nfq\Fairytale\CoreBundle\Entity\User
        category: Nfq\Fairytale\CoreBundle\Entity\Category
        book: Nfq\Fairytale\CoreBundle\Entity\Book
    data:
        type: orm
    ownership:
        "Nfq\Fairytale\CoreBundle\Entity\User": id

liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        book_big:
            quality: 75
            filters:
                thumbnail: { size: [300, 400], mode: outbound }
        book_medium:
            quality: 75
            filters:
                thumbnail: { size: [140, 180], mode: outbound }
        book_small:
            quality: 75
            filters:
                thumbnail: { size: [85, 133], mode: outbound }
        book_tiny:
            quality: 75
            filters:
                thumbnail: { size: [50, 60], mode: outbound }
        user_medium:
            quality: 75
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
        user_small:
            quality: 75
            filters:
                thumbnail: { size: [45, 45], mode: outbound }
