imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.yml }

framework:
    test: ~
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

nfq_fairytale_api:
    acl: api_acl_test.yml
    mapping:
        user: Nfq\Fairytale\CoreBundle\Entity\User

doctrine:
    dbal:
        dbname:   "%database_name%_test"
