Nfq\Fairytale\CoreBundle\Entity\Book:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        title:
            type: string
            length: 255
        description:
            type: text
        pages:
            type: integer
        publisher:
            type: string
            length: 255
        isbn:
            type: string
            lenhtg: 13
        cover:
            type: string
            length: 20
        language:
            type: string
            length: 20
        image:
            type: string
            length: 255
    manyToMany:
        categories:
            targetEntity: Category
            mappedBy: books
        authors:
            targetEntity: Author
            mappedBy: books
    oneToMany:
        ratings:
            targetEntity: Rating
            mappedBy: book
        comments:
            targetEntity: Comment
            mappedBy: book
        reservations:
            targetEntity: Reservation
            mappedBy: book
    lifecycleCallbacks: {}
