Nfq\Fairytale\CoreBundle\Entity\Book:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        genre:
            type: string
            length: 255
    manyToMany:
        categories:
            targetEntity: Category
            mappedBy: books
        authors:
            targetEntity: Author
            mappedBy: books
    oneToMany:
        ratings:
            targetEntity: Rating
            mappedBy: book
        comments:
            targetEntity: Comment
            mappedBy: book
    lifecycleCallbacks: {}
