Nfq\Fairytale\CoreBundle\Entity\Comment:
    type: entity
    id:
        id:
            type: integer
            generator:
            strategy: AUTO
    fields:
        content:
            type: text
        created:
            type: datetime
    manyToOne:
        user:
            targetEntity: User
            mappedBy: comments
        book:
            targetEntity: Book
            inversedBy: comments
    lifecycleCallbacks: {}
