Nfq\Fairytale\CoreBundle\Entity\Rating:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        value:
            type: smallint
        createdAt:
            type: datetime
    manyToOne:
        user:
            targetEntity: User
            inversedBy: ratings
        book:
            targetEntity: Book
            inversedBy: ratings
    lifecycleCallbacks: {}
