Nfq\Fairytale\CoreBundle\Entity\Reservation:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:  # reservation timestamp
            type: datetime
        takenAt:    # pick up from library timestamp
            type: datetime
            nullable: true
        returnedAt:    # returned to library timestamp
            type: datetime
            nullable: true
    manyToOne:
        user:
            targetEntity: User
            inversedBy: reservations
        book:
            targetEntity: Book
            inversedBy: reservations
    lifecycleCallbacks: {  }
