Nfq\Fairytale\CoreBundle\Entity\User:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        surname:
            type: string
            length: 255
    oneToMany:
        comments:
            targetEntity: Comment
            mappedBy: user
        ratings:
            targetEntity: Rating
            mappedBy: user
    manyToOne:
        reservedBook:
            targetEntity: Book
            inversedBy: reservedBy
    lifecycleCallbacks: {}
