Nfq\Fairytale\CoreBundle\Entity\User:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
    oneToOne:
        image:
            targetEntity: Image
            cascade: [persist, remove]
    oneToMany:
        comments:
            targetEntity: Comment
            mappedBy: user
        ratings:
            targetEntity: Rating
            mappedBy: user
        reservations:
            targetEntity: Reservation
            mappedBy: user
    lifecycleCallbacks: {}
