nfq_fairytale_frontend_homepage:
    path:     /
    defaults: { _controller: NfqFairytaleFrontendBundle:Default:index }
    methods: [GET]

partial:
    path:     /partial/{template}
    defaults: { _controller: NfqFairytaleFrontendBundle:Template:partial }
    requirements:
        _template: page1|page2
