parameters:
#    nfq_fairytale_frontend.example.class: Nfq\Fairytale\FrontendBundle\Example

services:
#    nfq_fairytale_frontend.example:
#        class: %nfq_fairytale_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
