forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/apt'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/ntp'
mod 'puppetlabs/git'
mod 'example42/iptables'
mod 'example42/php', '2.0.17'
mod 'willdurand/composer'
mod 'jfryman/nginx'
mod 'puppetlabs/mysql'
mod 'example42/hosts'
