parameters:
#    fairytale_core.example.class: Fairytale\CoreBundle\Example

services:
#    fairytale_core.example:
#        class: %fairytale_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
