Nfq\Fairytale\CoreBundle\Entity\Book:
    properties:
        comments:
            max_depth: 1
        ratings:
            max_depth: 1
        reservations:
            max_depth: 1
        categories:
            max_depth: 1
        authors:
            max_depth: 1
